site_name: Florian Sorko's Cheatsheets
site_description: 'Cheatsheets'
site_author: 'Florian Sorko'
repo_name: 'diepfote/cheatsheets'
repo_url: 'https://github.com/diepfote/cheatsheets'
theme:
  name: 'readthedocs'
